version: "3.8"

services:
  # ============================================
  # Backend API Service
  # ============================================
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod.microservices
    container_name: studysync-backend-prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGO_URI: ${MONGO_URI} # From .env
    expose:
      - "3000" # Only expose to internal network
    networks:
      - studysync-prod-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:3000/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  # ============================================
  # Frontend Service (Nginx + Static Files)
  # ============================================
  frontend:
    build:
      context: ./vue-project
      dockerfile: dockerfile.prod
    container_name: studysync-frontend-prod
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443" # For HTTPS (future)
    networks:
      - studysync-prod-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  studysync-prod-network:
    driver: bridge
