FROM node:24.3.0-alpine 

# Set working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to container
COPY package*.json ./

# Install ALL dependencies (including dev dependencies like nodemon)
# We use 'ci' to rely on the lock file for reproducible installs
RUN npm install

# Expose port
EXPOSE 3000

# CMD ["node", "server.js"]
CMD ["npm", "run", "dev"]