apiVersion: v1
kind: Service
metadata:
  name: studysync-backend
  namespace: studysync-prod
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: backend-port
