{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "studysync.fullname" . }}-backend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "studysync.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "studysync.backend.selectorLabels" . | nindent 4 }}
{{- end }}