{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "studysync.fullname" . }}-frontend
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "studysync.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  {{- if .Values.frontend.service.sessionAffinity }}
  sessionAffinity: {{ .Values.frontend.service.sessionAffinity }}
  {{- end }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "studysync.frontend.selectorLabels" . | nindent 4 }}
{{- end }}