{{- if and .Values.backend.enabled (not .Values.backend.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "studysync.fullname" . }}-backend-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "studysync.backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.backend.secrets.mongoUri }}
  MONGO_URI: {{ .Values.backend.secrets.mongoUri | b64enc | quote }}
  {{- end }}
  {{- if .Values.backend.secrets.jwtSecret }}
  JWT_SECRET: {{ .Values.backend.secrets.jwtSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.backend.secrets.sessionSecret }}
  SESSION_SECRET: {{ .Values.backend.secrets.sessionSecret | b64enc | quote }}
  {{- end }}
{{- end }}

{{/*
LEARNING NOTE: b64enc function
- Automatically base64 encodes the value
- No need to pre-encode like in plain YAML
- Helm does it at template render time

Security Best Practice:
- Don't put secrets in values.yaml (gets committed to Git)
- Pass via --set flag: --set backend.secrets.mongoUri="mongodb://..."
- Or use external secrets manager (AWS Secrets Manager)
*/}}